"""Pydantic schemas for face detection, face signatures (embeddings), and similarity comparison.

==================================================
EDUCATIONAL BREAKDOWN
==================================================

1. FACE SIGNATURE (EMBEDDINGS):
   - A Face Signature is a 128-dimensional floating-point vector produced by OpenCV SFace.
   - It maps facial geometry, texture, and feature ratios into a high-dimensional feature space.
   - IT IS NOT A LEGAL IDENTITY PROOF. It represents mathematical face correspondence between visual samples.

2. EMBEDDING FINGERPRINT (SHA-256 HASH):
   - To avoid exposing raw 128-float vectors unnecessarily through API responses and to prevent storing
     raw biometric vectors on-chain, we compute a cryptographic SHA-256 fingerprint hash of the embedding vector.

3. COSINE SIMILARITY & TERMINOLOGY:
   - Cosine Similarity measures the angular distance between two normalized 128-D embedding vectors in feature space.
   - Range: -1.0 to 1.0 (for normalized vectors, identical vectors yield 1.0; unrelated faces yield low scores).
   - Terminology: We describe matches as "face similarity", "face correspondence", or "matching score",
     NEVER as "absolute biometric identity proof".
"""

from typing import List, Optional
from pydantic import BaseModel, Field


class FacialLandmarks(BaseModel):
    """5-point facial landmark pixel coordinates [x, y]."""
    right_eye: List[float] = Field(..., description="[x, y] pixel coordinates of right eye center")
    left_eye: List[float] = Field(..., description="[x, y] pixel coordinates of left eye center")
    nose_tip: List[float] = Field(..., description="[x, y] pixel coordinates of nose tip")
    right_mouth: List[float] = Field(..., description="[x, y] pixel coordinates of right mouth corner")
    left_mouth: List[float] = Field(..., description="[x, y] pixel coordinates of left mouth corner")


class FaceSignature(BaseModel):
    """Numerical face representation metadata generated by OpenCV SFace."""
    embedding_generated: bool = Field(..., description="True if face embedding was successfully computed")
    embedding_dimension: int = Field(128, description="Dimensionality of SFace feature vector (default: 128)")
    embedding_hash: str = Field(..., description="Cryptographic SHA-256 fingerprint hex of raw embedding vector")
    norm: Optional[float] = Field(None, description="L2 norm of the embedding vector (should be ~1.0 when normalized)")


class FaceDetection(BaseModel):
    """Details of an individual face detected by YuNet."""
    confidence: float = Field(..., ge=0.0, le=1.0, description="Detection confidence score (face presence, NOT identity match)")
    bbox: List[int] = Field(..., min_length=4, max_length=4, description="Bounding box rectangle [x, y, width, height] in pixels")
    landmarks: Optional[FacialLandmarks] = Field(None, description="5-point facial landmarks if detected")
    signature: Optional[FaceSignature] = Field(None, description="Generated Face Signature embedding metadata")


class FaceDetectionResult(BaseModel):
    """Structured response output for face detection and signature extraction requests."""
    face_detected: bool = Field(..., description="True if one or more valid faces were detected")
    face_count: int = Field(..., ge=0, description="Total count of faces detected")
    faces: List[FaceDetection] = Field(default_factory=list, description="List of detected faces")
    image_width: Optional[int] = Field(None, description="Width of processed image in pixels")
    image_height: Optional[int] = Field(None, description="Height of processed image in pixels")
    error: Optional[str] = Field(None, description="Error explanation if detection or signature extraction failed")


class FaceSimilarityResult(BaseModel):
    """Structured response output for face signature similarity comparison."""
    matching_score: float = Field(..., description="Cosine similarity score between face signatures (-1.0 to 1.0)")
    correspondence_match: bool = Field(..., description="True if matching score exceeds configurable similarity threshold")
    threshold_used: float = Field(..., description="Cosine similarity threshold applied for decision boundary")
    face1_hash: Optional[str] = Field(None, description="SHA-256 fingerprint hash of primary face embedding")
    face2_hash: Optional[str] = Field(None, description="SHA-256 fingerprint hash of candidate face embedding")
    quality_assessment: str = Field(..., description="Qualitative face correspondence assessment (e.g. High Correspondence)")
    error: Optional[str] = Field(None, description="Error details if comparison failed")
